### ISSUE TITLE
Clipboard clearing

### ISSUE THREAD

**Issue by hakoptak** [betamos/clipboard-files#4]
Hi there,

Writing is currently not supported but would it be possible to add a clear() method?
Or would you accept a PR that adds it? I'm still a Rust novice but I could give it a try...

Besides that this is exactly what I need.

**Comment by betamos** [comment]
Sorry I just found this issue now. Yes, perhaps, but this isn't a general purpose clipboard library - only for files. There are probably better crates for setting and clearing the clipboard.

On the other hand, you could argue that if this crate can write (see #2), then it should also be able to clear. In practice, it probably depends on how easy it is to do using the current deps for each OS. PR welcome, but it should probably come after writing has been implemented.

**Comment by hakoptak** [comment]
Just to let you know that I found a clipboard for Tauri that includes your clipboard logic and there a clear() method made sense. So no need to implement it anymore.

Thanks for following up.
